/*
 *  The contents of this file are subject to the Initial
 *  Developer's Public License Version 1.0 (the "License");
 *  you may not use this file except in compliance with the
 *  License. You may obtain a copy of the License at
 *  http://www.ibphoenix.com/main.nfs?a=ibphoenix&page=ibp_idpl.
 *
 *  Software distributed under the License is distributed AS IS,
 *  WITHOUT WARRANTY OF ANY KIND, either express or implied.
 *  See the License for the specific language governing rights
 *  and limitations under the License.
 *
 *  The Original Code was created by Mark O'Donohue
 *  for the Firebird Open Source RDBMS project.
 *
 *  Copyright (c) 2002 Mark O'Donohue <skywalker@users.sourceforge.net>
 *  and all contributors signed below.
 *
 *  All Rights Reserved.
 *  Contributor(s): ______________________________________.
 *
 *  2005.05.19 Claudio Valderrama: signal tokens that aren't reserved in the
 *      engine thanks to special handling.
 *  Adriano dos Santos Fernandes
 */

#include "keywords.h"

// CVC: The latest column indicates whether the token as special handling in
// the parser. If it does, KEYWORD_stringIsAToken will return false.
// I discovered isql was being fooled and put double quotes around those
// special cases unnecessarily.

#define false 0
#define true 1

struct tok tokens[] =
{
	{"!<", false},
	{"!=", false},
	{"!>", false},
	{"(", false},
	{")", false},
	{",", false},
	{"<", false},
	{"<=", false},
	{"<>", false},	// Alias of !=
	{"=", false},
	{">", false},
	{">=", false},
	{"ABS", false},
	{"ACCENT", true},
	{"ACOS", false},
	{"ACTION", true},
	{"ACTIVE", false},
	{"ADD", false},
	{"ADMIN", false},
	{"AFTER", false},
	{"ALL", false},
	{"ALTER", false},
	{"ALWAYS", true},
	{"AND", false},
	{"ANY", false},
	{"AS", false},
	{"ASC", false},	// Alias of ASCENDING
	{"ASCENDING", false},
	{"ASCII_CHAR", false},
	{"ASCII_VAL", false},
	{"ASIN", false},
	{"AT", false},
	{"ATAN", false},
	{"ATAN2", false},
	{"AUTO", false},
	{"AVG", false},
	{"BACKUP", true},
	{"BEFORE", false},
	{"BEGIN", false},
	{"BETWEEN", false},
	{"BIGINT", false},
	{"BIN_AND", false},
	{"BIN_OR", false},
	{"BIN_SHL", false},
	{"BIN_SHR", false},
	{"BIN_XOR", false},
	{"BIT_LENGTH", false},
	{"BLOB", false},
	{"BLOCK", true},
	{"BOTH", false},
	{"BREAK", true},
	{"BY", false},
	{"CASCADE", true},
	{"CASE", false},
	{"CAST", false},
	{"CEIL", false},	// alias of CEILING
	{"CEILING", false},
	{"CHAR", false},
	{"CHAR_LENGTH", false},
	{"CHARACTER", false},
	{"CHARACTER_LENGTH", false},
	{"CHECK", false},
	{"CLOSE", false},
	{"COALESCE", true},
	{"COLLATE", false},
	{"COLLATION", true},
	{"COLUMN", false},
	{"COMMENT", true},
	{"COMMIT", false},
	{"COMMITTED", false},
	{"COMPUTED", false},
	{"CONDITIONAL", false},
	{"CONNECT", false},
	{"CONSTRAINT", false},
	{"CONTAINING", false},
	{"COS", false},
	{"COSH", false},
	{"COT", false},
	{"COUNT", false},
	{"CREATE", false},
	{"CROSS", false},
	{"CSTRING", false},
	{"CURRENT", false},
	{"CURRENT_CONNECTION", false},
	{"CURRENT_DATE", false},
	{"CURRENT_ROLE", false},
	{"CURRENT_TIME", false},
	{"CURRENT_TIMESTAMP", false},
	{"CURRENT_TRANSACTION", false},
	{"CURRENT_USER", false},
	{"CURSOR", false},
	{"DATABASE", false},
	{"DATE", false},
	{"DATEADD", false},
	{"DATEDIFF", false},
	{"DAY", false},
	{"DEBUG", false},
	{"DEC", false},
	{"DECIMAL", false},
	{"DECLARE", false},
	{"DECODE", false},
	{"DEFAULT", false},
	{"DELETE", false},
	{"DELETING", true},
	{"DESC", false},	// Alias of DESCENDING
	{"DESCENDING", false},
	{"DESCRIPTOR", true},
	{"DIFFERENCE", true},
	{"DISCONNECT", false},
	{"DISTINCT", false},
	{"DO", false},
	{"DOMAIN", false},
	{"DOUBLE", false},
	{"DROP", false},
	{"ELSE", false},
	{"END", false},
	{"ENTRY_POINT", false},
	{"ESCAPE", false},
	{"EXCEPTION", false},
	{"EXECUTE", false},
	{"EXISTS", false},
	{"EXIT", false},
	{"EXP", false},
	{"EXTERNAL", false},
	{"EXTRACT", false},
	{"FETCH", false},
	{"FILE", false},
	{"FILTER", false},
	{"FIRST", true},
	{"FLOAT", false},
	{"FLOOR", false},
	{"FOR", false},
	{"FOREIGN", false},
	{"FREE_IT", true},
	{"FROM", false},
	{"FULL", false},
	{"FUNCTION", false},
	{"GDSCODE", false},
	{"GENERATED", true},
	{"GENERATOR", false},
	{"GEN_ID", false},
	{"GEN_UUID", false},
	{"GLOBAL", false},
	{"GRANT", false},
	{"GROUP", false},
	{"HASH", false},
	{"HAVING", false},
	{"HOUR", false},
	{"IF", false},
	{"IGNORE", true},
	{"IIF", true},
	{"IN", false},
	{"INACTIVE", false},
	{"INDEX", false},
	{"INNER", false},
	{"INPUT_TYPE", false},
	{"INSENSITIVE", false},
	{"INSERT", false},
	{"INSERTING", true},
	{"INT", false},
	{"INTEGER", false},
	{"INTO", false},
	{"IS", false},
	{"ISOLATION", false},
	{"JOIN", false},
	{"KEY", false},
	{"LAST", true},
	{"LEADING", false},
	{"LEAVE", true},
	{"LEFT", false},
	{"LENGTH", false},
	{"LEVEL", false},
	{"LIKE", false},
	{"LIMBO", true},
	{"LIST", false},
	{"LN", false},
	{"LOCK", true},
	{"LOG", false},
	{"LOG10", false},
	{"LONG", false},
	{"LOWER", false},
	{"LPAD", false},
	{"MANUAL", false},
	{"MATCHED", false},
	{"MATCHING", false},
	{"MAX", false},
	{"MAXVALUE", false},
	{"MAXIMUM_SEGMENT", false},
	{"MERGE", false},
	{"MILLISECOND", false},
	{"MIN", false},
	{"MINUTE", false},
	{"MINVALUE", false},
	{"MOD", false},
	{"MODULE_NAME", false},
	{"MONTH", false},
	{"NAMES", false},
	{"NATIONAL", false},
	{"NATURAL", false},
	{"NCHAR", false},
	{"NEXT", true},
	{"NO", false},
	{"NOT", false},
	{"NULLIF", true},
	{"NULL", false},
	{"NULLS", true},
	{"NUMERIC", false},
	{"OCTET_LENGTH", false},
	{"OF", false},
	{"ON", false},
	{"ONLY", false},
	{"OPEN", false},
	{"OPTION", false},
	{"OR", false},
	{"ORDER", false},
	{"OUTER", false},
	{"OUTPUT_TYPE", false},
	{"OVERFLOW", false},
	{"OVERLAY", false},
	{"PAD", true},
	{"PAGE", false},
	{"PAGES", false},
	{"PAGE_SIZE", false},
	{"PARAMETER", false},
	{"PASSWORD", false},
	{"PI", false},
	{"PLACING", false},
	{"PLAN", false},
	{"POSITION", false},
	{"POST_EVENT", false},
	{"POWER", false},
	{"PRECISION", false},
	{"PRESERVE", true},
	{"PRIMARY", false},
	{"PRIVILEGES", false},
	{"PROCEDURE", false},
	{"PROTECTED", false},
	{"RAND", false},
	{"RDB$DB_KEY", false},
	{"READ", false},
	{"REAL", false},
	{"RECORD_VERSION", false},
	{"RECREATE", false},
	{"RECURSIVE", false},
	{"REFERENCES", false},
	{"RELEASE", false},
	{"REPLACE", false},
	{"REQUESTS", true},
	{"RESERV", false},	// Alias of RESERVING
	{"RESERVING", false},
	{"RESTART", true},
	{"RESTRICT", true},
	{"RETAIN", false},
	{"RETURNING", true},
	{"RETURNING_VALUES", false},
	{"RETURNS", false},
	{"REVERSE", false},
	{"REVOKE", false},
	{"RIGHT", false},
	{"ROLE", true},
	{"ROLLBACK", false},
	{"ROUND", false},
	{"ROW_COUNT", false},
	{"ROWS", false},
	{"RPAD", false},
	{"SAVEPOINT", false},
	{"SCALAR_ARRAY", true},
	{"SCHEMA", false},	// Alias of DATABASE
	{"SECOND", false},
	{"SEGMENT", false},
	{"SELECT", false},
	{"SENSITIVE", false},
	{"SEQUENCE", true},
	{"SET", false},
	{"SHADOW", false},
	{"SHARED", false},
	{"SIGN", false},
	{"SIN", false},
	{"SINGULAR", false},
	{"SINH", false},
	{"SIZE", false},
	{"SKIP", true},
	{"SMALLINT", false},
	{"SNAPSHOT", false},
	{"SOME", false},
	{"SORT", false},
	{"SPACE", true},
	{"SQLCODE", false},
	{"SQRT", false},
	{"STABILITY", false},
	{"START", false},
	{"STARTING", false},
	{"STARTS", false},	// Alias of STARTING
	{"STATEMENT", true},
	{"STATISTICS", false},
	{"SUBSTRING", true},
	{"SUB_TYPE", false},
	{"SUM", false},
	{"SUSPEND", false},
	{"TABLE", false},
	{"TAN", false},
	{"TANH", false},
	{"TEMPORARY", true},
	{"THEN", false},
	{"TIME", false},
	{"TIMESTAMP", false},
	{"TIMEOUT", true},
	{"TO", false},
	{"TRAILING", false},
	{"TRANSACTION", false},
	{"TRIGGER", false},
	{"TRIM", false},
	{"TRUNC", false},
	{"TYPE", true},
	{"UNCOMMITTED", false},
	{"UNDO", true},
	{"UNION", false},
	{"UNIQUE", false},
	{"UPDATE", false},
	{"UPDATING", true},
	{"UPPER", false},
	{"USER", false},
	{"USING", false},
	{"VALUE", false},
	{"VALUES", false},
	{"VARCHAR", false},
	{"VARIABLE", false},
	{"VARYING", false},
	{"VIEW", false},
	{"WAIT", false},
	{"WEEK", false},
	{"WEEKDAY", true},
	{"WHEN", false},
	{"WHERE", false},
	{"WHILE", false},
	{"WITH", false},
	{"WORK", false},
	{"WRITE", false},
	{"YEAR", false},
	{"YEARDAY", true},
	{"^<", false},	// Alias of !<
	{"^=", false},				// Alias of !=
	{"^>", false},			// Alias of !>
	{"||", false},
	{"~<", false},	// Alias of !<
	{"~=", false},				// Alias of !=
	{"~>", false},			// Alias of !>
	{0, false}
};

/* This method is currently used in isql/isql.epp to check if a
   user field is a reserved word, and hence needs to be quoted.
   Obviously a hash table would make this a little quicker.

   MOD 29-June-2002
*/

int IsAToken(const char* in_str)
{
    struct tok *tok_ptr = (struct tok*)&tokens;
    while (tok_ptr->tok_string) {
        if (!tok_ptr->nonReserved && !strcasecmp(tok_ptr->tok_string, in_str)) {
            return true;
        }
        ++tok_ptr;
    }
    return false;
}
